# Utilizar la imagen base de nginx
FROM nginx:latest

# Copiar el archivo index.html al directorio de contenido de nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80
EXPOSE 80
